### ISSUE TITLE
Interpro OBO?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_interpro#12]
Does anyone have an interpro OBO to load?

If not we'll develop a converter.

They have a terms/definition file, and a relationships file, and I found a script someone wrote in java to convert the relationships to OBO
https://www.biostars.org/p/16699/

**Comment by jwest60** [comment]
a converter and obo file can now be found [here](https://github.com/jwest60/iprobo)

**Comment by bradfordcondon** [comment]
the interpro vocabulary isnt highly structured, making hte benefits of offering a browser pretty null.  Because of that I'm going to c lose this, but thank you @jwest60 for working out an OBO file.
