### ISSUE TITLE
delta value for field is kind of strange 

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_interpro#15]
https://github.com/tripal/tripal_analysis_interpro/blob/c4a123e2d033f5d849350d67ac1f4ff707c932ad/includes/TripalFields/local__interpro_results/local__interpro_results.inc#L49-L69

* delta 0 is always going to be undefined
* other deltas are the analysis ID.

I would think that delta should go 0, 1, 2, and there should be an analysis_id key next to parsed.

**Comment by bradfordcondon** [comment]
Heres the resulting `$items` in the formatter.  You can see i have one analysis (144), and that theres an undefined entry for `$item[0]`

![image](https://user-images.githubusercontent.com/7063154/45369345-aa8de700-b5b3-11e8-9cfd-9d47b0cbf030.png)

**Comment by laceysanderson** [comment]
I agree that it should be as you expect
> I would think that delta should go 0, 1, 2, and there should be an analysis_id key next to parsed.

**Comment by bradfordcondon** [comment]
Upon further consideration, the $analysis object is inside the "parsed" array, so there really is no need for an `analysis_id` key.  The formatterdoes not use the $item position key as the analysis id, for example: it uses the analysis object in `parsed`.

**Comment by bradfordcondon** [comment]
this was merged, closing.
