### ISSUE TITLE
unpublish interpro results

### ISSUE THREAD

**Issue by kyrenya** [tripal/tripal_analysis_interpro#25]
Hi there!
How is it possible to unpublish InterPro results? I've tried unpublishing and deleting the analysis, but the results are still displayed. 
Where in the chado tables are the records of a interpro xml file upload stored? 
Thanks in advance.

**Comment by bradfordcondon** [comment]
hi @kyrenya the annotations themselves go in `feature_cvterm` (the interpro and GO accessions).  These are what show up in the "annotations" field.

The XML itself goes in `analysisfeatureprop`, under the term `analysis_interpro_xmloutput_hit`.    This is waht goes in the Interpro visualization field.

The easiest way would be to drop the features (which would cascade to the other tables such as feature_cvterm), and reload the FASTA and GFF files.  If youre just interested in dropping the v isualization, but are OK keeping hte annotations in `feature_cvterm`, you can delete the `analysisfeature` records associated with the analysis you loaded.

Let me know if that answers your question.

**Comment by kyrenya** [comment]
yes, indeed! 
Thanks a lot!
