### ISSUE TITLE
InterPro Results filter in search

### ISSUE THREAD

**Issue by martacsilva** [tripal/tripal_analysis_interpro#31]
Hi!
I have uploaded my InterPro results to my portal and everything is looking good, they show up in my individual pages in the tab InterPro results.
However I would like to be able to filter by IPR term in my searches, but the only option I see available is InterPro results. 
![Screenshot (173)](https://user-images.githubusercontent.com/47527249/72077700-97963e80-32ef-11ea-8987-90cf671c1530.png)
![Screenshot (174)](https://user-images.githubusercontent.com/47527249/72077724-a250d380-32ef-11ea-807e-077292896e7a.png)

When I try to use it, it just outputs the full list of features I have available so I think that either it's not what I want or it's not working as it should. 

I would really like to be able to filter my searches by the IPR terms. Any help would be much appreciated!

Thanks in advance, 
Marta

P.S.: Could it have something to do with the .XML? Does it have to be a unique file or multiple files for each feature?

**Comment by martacsilva** [comment]
I have since been trying to use the filter of Annotation Term Accession and it still outputs all results when I search for a specific term.
![Screenshot (60)](https://user-images.githubusercontent.com/47527249/84768712-98cd4500-afcc-11ea-9b5d-3ff89717f268.png)
The terms are there as you can see in the last column but the filter is not working properly.

Can you help me fix this or at least point me in the right direction?
Thank you!

**Comment by laceysanderson** [comment]
Hi @martacds,

I've consulted with @bradfordcondon and @almasaeed2010 and may have an idea where the problem lies. 

In Drupal Views, "InterPro results" is provided by the [local__interpro_results](https://github.com/tripal/tripal_analysis_interpro/blob/7.x-3.x/includes/TripalFields/local__interpro_results/local__interpro_results.inc) ChadoField. Unfortunately the [elementInfo()](local__interpro_results) and [query()](https://tripal.readthedocs.io/en/latest/dev_guide/custom_field/manual_field_creation.html#query-function) methods were not implemented. 

According to the Tripal Docs:
> As described above in the elementInfo function section, some fields and elements of fields are searchable. if the elementInfo array indicates that the field is searchable and has operations (i.e. filters) then we must provide a way for those queries to occur. This is where the query() function is needed. 

So I believe those two methods will need to be implemented in order for searching to work on that field. I've linked to the developer docs regarding those methods and also the field which needs to be updated. Your annotations are stored in the `feature_cvterm` table in chado. Unfortunately I do not have time nor data to work on this further as it's not my module but maybe that will give you a start?

**Comment by martacsilva** [comment]
Thank you for the help! I will try to see if I can do something with that info.

**Comment by bradfordcondon** [comment]
This module puts the interpro annotations in two places.   One place is the field this module provides: `local__interpro_results` which **doesnt** look in `feature_cvterm` but instead `analysisfeature` and as Lacey points out, doesnt have search properly implemented.

I think a solution might be to use Tripal core's [`sio__annotation`](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/sio__annotation/sio__annotation.inc) field.  @laceysanderson  says it should appear  as "Annotations" in the Drupal view.  Can you try using that one instead?   That field **does** have a search implemented, looking in `feature_cvterm`.

**Comment by martacsilva** [comment]
Thank you for the extra help!

From what I understood of what you said, I should look for an "Annotations" in my Search filters. But I don't have it....
![Screenshot (85)](https://user-images.githubusercontent.com/47527249/87024457-0d149600-c1d1-11ea-82cd-a043500eac6b.png)

I have also tried to use Annotation Term Accession (screenshot from my second comment) which is correctly populated (I assume) because the info shows up in the last column of the results.

What I want is for users to be able to filter Tripal Content by IPR and GO terms, if that helps.

**Comment by martacsilva** [comment]
Hi everyone!

Still haven't been able to fix this issue (see above comment). Sorry to keep bothering you but I'm a beginner in all of this and haven't been able to figure it out by myself.

To recap: I don't have an Annotations filter, but I do have an Annotation Term Accession filter that is populated and working as a field but not as a filter (see my 2nd comment on this thread - Jun 16).

Thank you!

**Comment by bradfordcondon** [comment]
hi @martacds   have you tried checking for new fields on the Polypeptide bundle?   Basically you need the `Annotations` field from Tripal Core.  The field included with this module doesnt have the methods written.

**Comment by martacsilva** [comment]
Hi @bradfordcondon , 
Thanks for answering. Yes, i have checked for new fields but it says that no new ones were added, which makes sense since Annotations is indeed one of the fields present in the Polypeptide Content Type.
![Screenshot (103)_LI](https://user-images.githubusercontent.com/47527249/89554421-bcf81600-d806-11ea-9ea5-406e680e355d.jpg)

The problem is that it doesn't show up as a possible filter in the search (see previous message). But Polypeptides do have Annotations and the fields are populated.
![Screenshot (104)](https://user-images.githubusercontent.com/47527249/89554331-a0f47480-d806-11ea-94f8-3fea38f7670b.png)

**Comment by spficklin** [comment]
Hi @martacds 

I just tested setting up a search using the "Annotation Term Accession".  I imported some InterPro results and I think the field has a bug in it. It's definitely not filtering correctly.  I'll look into it.  But, I also think there may be a problem with what you expect the results to look like?  Is it okay to have all of the IPR terms for each record listed or are you expecting to only see the term searched for in the result table?

**Comment by spficklin** [comment]
Hi @martacds .  I spent a bit of time and found that there is a bug in the core Tripal code that was causing the problem!  I just submitted a Pull Request on the Tripal core repository that I think will fix the problem for you.  The PR is here:  https://github.com/tripal/tripal/pull/1075

This I think will fix the problem of the field not search for you.  It doesn't change anything with the way the terms are displayed in the results.

Would you be able to test it for us to see if works for you?  We always need two people to test a PR before it gets merged as an official fix.  So, if you could help with that, getting the fix into Tripal will go a bit faster.  If you are comfortable working with git to switch branches for testing let us know and we can provide instructions.

**Comment by martacsilva** [comment]
Hi @spficklin ! Thank you so much for the help!
In terms of what the results look like, it's perfectly fine for all terms to appear. Actually it might even be a plus.

I believe I still have instructions from a previous issue on how to test a branch, I'll find it and test it ASAP.

**Comment by martacsilva** [comment]
It works! :) 
![Screenshot (107)](https://user-images.githubusercontent.com/47527249/89620444-8ca48c00-d887-11ea-978e-304956f82049.png)

**Comment by bradfordcondon** [comment]
we've merged this in Tripal core, so i will close this issue. Thank you @martacds  and @spficklin
