### ISSUE TITLE
PHP8 Issues

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal_analysis_interpro#32]
The following error appears three times under PHP 8.0 when running a database update for a different module

```Deprecated: Required parameter $query_type follows optional parameter $seqname in /local/sites/dev.carrotomics.org/drupal-7.69/sites/all/modules/tripal_analysis_interpro/includes/TripalImporter/InterProImporter.inc on line 494```

this is because of the following function definition at line 494
```
  function matchFeature($seqid, $seqname = '',
      $query_re, $query_uniquename, $query_type) {
```
This function is only called in two places, ```$seqname``` always has a value (I think) so just drop the ``` = ''```?

**Comment by bradfordcondon** [comment]
sounds reasoanble.  Maybe drop the optional paameter part, and add a 

```php

if (!$seqname) {
$seqname = "";
 }
```
