### ISSUE TITLE
Publishing Requires Analysis ID

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal_analysis_interpro#9]
When publishing interPro results, there is a required field in the filters section called "Data Source Name" that prompts for a string but runs a query looking for the Analysis ID, which is causing an SQL error.

```
Job execution failed: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "data source interpro"                                                                                             [error]
LINE 1: ...T.value = 'interpro_analysis' AND T.analysis_id = 'data sour...
```

Thanks!

**Comment by almasaeed2010** [comment]
We noticed that this issue also exists for the `tripal/tripal_analysis_blast` module.

**Comment by bradfordcondon** [comment]
I think this is resolved, what say you @almasaeed2010

**Comment by almasaeed2010** [comment]
Yes I think this is resolved. (sorry for the delay!)
